
const {
	NOTIFICATION_ORDER,
	NOTIFICATION_REVIEW,
	NOT_AVAILABLE_TRUCK,
	AVAILABLE_TRUCK,
	BUSY_TRUCK,
	HOLD_TRUCK,
	SUSPENDED_TRUCK,
	DRIVER_LICENSE_TYPE_A,
	DRIVER_LICENSE_TYPE_B,
	DRIVER_LICENSE_TYPE_C,
	DRIVER_LICENSE_TYPE_M,
	DRIVER_LICENSE_TYPE_A_CDL,
	DRIVER_LICENSE_TYPE_M_CDL,
	DRIVER_LICENSE_TYPE_C_CDL,
	INCHES,
	FEET,
	POUNDS,
	NOT_AVAILABLE_DRIVER,
	AVAILABLE_DRIVER,
	BUSY_DRIVER,
	HOLD_DRIVER

} = require('../constants/db');

const enumVars = {
	userStatus: [0, 1, 2],
	userRole: ['admin', 'hr', 'dispatcher'],
	registeredFrom: ['APP', 'FB', 'PC', 'APPLE', 'WECHAT', 'WEB'],
	deviceType: [1, 2, 3],
	GENDER: ['Male', 'Female', 'Others'],
	NOTIFICATION_TYPE: [NOTIFICATION_ORDER, NOTIFICATION_REVIEW],
	TRUCK_STATUS: [NOT_AVAILABLE_TRUCK, AVAILABLE_TRUCK, HOLD_TRUCK, BUSY_TRUCK, SUSPENDED_TRUCK],
	TRUCK_STATUS_UPDATABLE_BY_DRIVER: [NOT_AVAILABLE_TRUCK, AVAILABLE_TRUCK],
	DRIVER_STATUS: [NOT_AVAILABLE_DRIVER, AVAILABLE_DRIVER, BUSY_DRIVER, HOLD_DRIVER],
	TRUCK_DIMENSION_TYPE: [INCHES, FEET],
	WEIGHT_TYPE: [POUNDS],
	DRIVER_LICENSE_TYPE: [DRIVER_LICENSE_TYPE_A, DRIVER_LICENSE_TYPE_B, DRIVER_LICENSE_TYPE_C, DRIVER_LICENSE_TYPE_M,
		DRIVER_LICENSE_TYPE_A_CDL,
		DRIVER_LICENSE_TYPE_M_CDL,
		DRIVER_LICENSE_TYPE_C_CDL,]
};

module.exports = enumVars;
